---
version: "3.7"

services:
  rdf-usage-stats:
    image: "crc-datasite-template"
    container_name: "crc-datasite-template"
    hostname: "crc-datasite-template"
    restart: "on-failure"
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - "./src:/app"
    build:
      context: "./src"
      dockerfile: "../docker/flask/Dockerfile"
...

